<?php
    // TODO: add forward slash to the root path at the end if not present
    // TODO: add graphics path in admin and default it to external indicator folder with old and new indicators

    $helper = $this->helper('WebRotate360\ProductViewerAdHoc\Helper\Data');
    if (!$helper)
        return;

    $popupMode  = $helper->getPopupMode();
    $rootPath   = $helper->getWebrotateRootUrl();
    $configPath = $helper->getWebrotatePath();

    if (empty($configPath)) {
        $configPath = $helper->getMasterConfigUrl();
        if (!empty($configPath))
            $isMasterMode = true;
    }

    $isAdhocOn = (!isset($isMasterMode) && !empty($configPath)) || (isset($isMasterMode) && !empty($rootPath));

    $configBaseUrl = $helper->getBaseUrl();
    if ($helper->getUseMediaUrlConfig() === true) {
        $configBaseUrl = $helper->getMediaUrl();
    }
?>

<?php if ($isAdhocOn): ?>
    <?php $configPath = strpos($configPath, 'https://') === 0 ? $configPath : $configBaseUrl . $configPath; ?>
    <?php if ($helper->isEmbedded()): ?>
        <link  rel="stylesheet" type="text/css" href="<?php echo $helper->getViewerSkinUrl() ?>" />
        <style type="text/css">
            <?php echo $helper->getPlaceholder() ?>{visibility: hidden;}
        </style>
        <script language="javascript" type="text/javascript">
            require(['jquery'], function(jQuery){
                require(['imagerotator', 'wr360hook'], function() {
                    (function() {
                        jQuery(document).ready(function () {
                            WR360AdhocEmbedInitialize( {
                                pagePlaceholder: "<?php echo $helper->getPlaceholder() ?>",
                                viewerWidth: "<?php echo $helper->getViewerWidth() ?>",
                                viewerHeight: "<?php echo $helper->getViewerHeight() ?>",
                                baseWidth: <?php echo $helper->getBaseWidth()?>,
                                graphicsPath: "<?php echo $helper->getGraphicsPathUrl() ?>",
                                confFileURL: "<?php echo $configPath ?>",
                                rootPath: "<?php echo $rootPath ?>",
                                licensePath: "<?php echo $helper->getLicense() ?>",
                                minHeight: <?php echo $helper->getMinHeight() ?>,
                                useAnalytics: <?php $helper->isUseAnalytics() ? print("true") : print("false") ?>,
                                apiCallback: "<?php echo $helper->getApiCallback() ?>"
                            });
                        });
                    })(jQuery);
                });
            });
        </script>
    <?php else:?>
        <link  rel="stylesheet" type="text/css" href="<?php ($popupMode == $helper::POPUP_MODE_LIGHTBOX) ?
            print($helper->getPopupSkinUrl()) : print($helper->getViewerSkinUrl()) ?>" />
        <style type="text/css">
            <?php echo $helper->getPlaceholder() ?>{visibility: hidden;}
        </style>
        <script language="javascript" type="text/javascript">
            <?php if ($popupMode == $helper::POPUP_MODE_LIGHTBOX): ?>
                require(['jquery'], function(jQuery){
                    require(['imagerotator', 'prettyPhoto', 'wr360hook'], function(){
                        (function() {
                            jQuery(document).ready(function () {
                                <?php
                                    $popupRefHrf = sprintf(
                                        "%s?config=%s&root=%s&height=%s&lic=%s&grphpath=%s&analyt=%s&iframe=true&width=%s&height=%s",
                                        $helper->getFrameUrl(),
                                        urlencode($configPath),
                                        urlencode($rootPath),
                                        $helper->getViewerHeight(),
                                        urlencode($helper->getLicense()),
                                        urlencode($helper->getGraphicsPathUrl()),
                                        $helper->isUseAnalytics() ? print("1") : print("0"),
                                        $helper->getViewerWidth(),
                                        $helper->getViewerHeight());
                                ?>

                                WR360AdhocPopupInitialize(
                                    "<?php echo $helper->getPlaceholder() ?>",
                                    "<?php echo $popupRefHrf ?>",
                                    "<?php echo $helper->getPopupIconUrl() ?>",
                                    "<?php echo $helper->getPrettyTheme() ?>");
                            });
                        })(jQuery);
                    });
                });
            <?php else:?>
                require(['jquery'], function(jQuery){
                    require(['imagerotator', 'wr360hook'], function() {
                        (function() {
                            jQuery(document).ready(function () {
                                WR360AdhocFullScreenClickInitialize( {
                                    pagePlaceholder: "<?php echo $helper->getPlaceholder() ?>",
                                    thumbPath: "<?php echo $helper->getPopupIconUrl() ?>",
                                    graphicsPath: "<?php echo $helper->getGraphicsPathUrl() ?>",
                                    configFileURL: "<?php echo $configPath ?>",
                                    rootPath: "<?php echo $rootPath ?>",
                                    licensePath: "<?php echo $helper->getLicense() ?>",
                                    useAnalytics: <?php $helper->isUseAnalytics() ? print("true") : print("false") ?>,
                                    apiCallback: "<?php echo $helper->getApiCallback() ?>",
                                    inBrowser: <?php $popupMode == $helper::POPUP_MODE_BROWSER_WINDOW ? print("true") : print("false") ?>
                                });
                            });
                        })(jQuery);
                    });
                });
            <?php endif?>
        </script>
    <?php endif?>
<?php endif?>
